### ISSUE TITLE
Save the Shopify discount information

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#84]
This issue scope changed. See https://github.com/tiki/integrations/issues/84#issuecomment-1589484579.

When the user accepts the license, a new License is created. With the License's ID, we make a Payable through TIKI SDK JS to store the discount information.

The values for this Payable creation should be added in the app-theme-block:
 - amount: The amount of the discount
 - type: percentage or fixed-value
 - description: the human-readable discount description
 - expiry: expiration date. If null, it is a one-time payable. If set, the usage is unlimited until expired.

These values are passed to the TIKI_SETTINGS js object. On license acceptance, the License is used to create a payable:
- on accept callback for logged in users
- in the cookie verification for not logged in users

Update the discount function to use these values instead of the hard-coded ones, defined in #76.

**Comment by ricardobrg** [comment]
The amount, expiry and type will come from the discount configuration. Using fixed values for now.
The description will be the same from the offer license as a placeholder. It should be changed later for something that could be edited (maybe in the discounts interface?)

**Comment by ricardobrg** [comment]
The discount information is saved by posting it the `/api/latest/discount` endpoint.

The discount gid is saved in the user Payable registry and retrieved when the discount is applied by the discount function.

We don't need to use 2 different UIs for the product/order discounts. It could be just one, with a switcher, and this information should be saved in the discount options object. #109 will handle this

**Comment by ricardobrg** [comment]
Taking back the change in the UIs, in #111 I am updating the UIs to follow Shopify, with 2 pages for order and product discounts.

**Comment by mike-audi** [comment]
This will be refactored to be consistent with both the standard Oauth2.0 spec and the Shopify's token security pattern of decoupling session tokens from access token in #113
